server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://124.222.129.50:3306/blog?serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver