server:
  port: 8001

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    port: 6379
    host: localhost
    #    password:
    database: 0
    jedis:
      pool:
        max-idle: 8
        max-active: 16
        min-idle: 4
mybatis-plus:
  #指定xml映射文件位置，多个时逗号分隔
  mapper-locations: classpath:mapper/**.xml
logging:
  level:
    com.ybh.blog.mapper: debug